import numpy as np
# n=int(input("enter number of elements:"))
# f=np.array([],dtype=int)
# a=np.array([],dtype=int)
# for i in range(n):
#     v=int(input("enter element:"))
#     a=np.append(a,v)
# print("aray is:",a)
# b=np.sort(a)
# print("sorted array is:",b)
# c=np.mean(a)
# print("mean is:",c)
# d=np.median(a)
# print("median is:",d)
# e=np.std(a)
# print("standard deviation is:",e)
# f=np.multiply(a,a)
# print("dot product is:",f)
# g=np.add(a,a)
# print("sum is:",g)
# a=np.delete(a,-1)
# print("after removing last element:",a)
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(myArray)
c=myArray[0:2, :] = 0
print(myArray)
